sudo: false
language: node_js
node_js:
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: PAKu2TOy3lAfvweEW7vRM+hJTXacHkymsT/f3D59PbaZSsMUoPTuoHSZFZ8w+eyyTm8wr8IWZoja52IRIEZP/0SMSfhdw22uuedR+5k7Y9YtijbEtlH1Lu/3Cm1SUg9YRiX8iN1g4Q10ss8vcOdAviEhTnNUwqedCxvYWAbIagOSJuTXWl47iFJfVKDPyNwE0UKa/ytjJWM3Wuf9xjkmCCSTuH/lL6QSa8YM7s5grnBAVG0zQNPloWhwdZ15895hl6zfhhrOpD5MmpWSfsaucPNb2F5HQcUx4JJUPhv0/bweKS+ii0DEHpi+yj/nYVKvl5z5b53CYQ9zz+g1+wXXVJZ5cRRbkiep9xUPuDw6pYrMrSrw1u7vfiVBg/Nc/OwrLxoF4CG/oYLZfx2mN4CzTdVGFbz3CsS55Z/F1R5MxM0RN3yjh3OWmUcNIBK7T5htEqPBEvihKAiAmxRxGSqqFkelyTj2LTKF0biTmvH4K0Bm699krNDKEy0fSD7iXDM/xojtO4+Y9C5tG4CJoyUsAl+loYz5Rv2F6M1/3idMKEmN1fL7Nk1pKFklONkpqaUow8TdlbZbrZfvUwhBe3JemYWjxhhQkiq5DFO+irGPB0+n0S1SX3L7h9tWqwxTedyT9N0oAKfoKvnx+5Rgs6H4mseHatG4kkQ8rI8bnbxPV4I=
  email:
    recipients:
      secure: cBZKK4ol7uhiT3APoO6YEjLTdJXoESYnGwGaLHzCGx+h9rEf/YZG2KzCvUEvrvVxLfXXp37zDFQMTX+8X+r8YvLPe9379pOv8dfVeqpVBwMdOqN4KL9wSUaBy+Sj3nEyhrMwJeYpmRwXdkluTp62+RbY+NmVFav9hWjE8sXJ6NCtXIyP151zD+k+md/pu/wWYFARXBID1ZeIXQ5Dg8VAzm2Ied6FFx190o3IB36AAE/0Au939E8Y/br46ncebxDuw52rQCHkt4QIpr4jf3hU5CkGsxEZP49eacDrg8jHEjRM0zBgpo0UhuH9sT5u7rf1SkMKN18bFTHkPTDLGiri85uA5B6TA+8/HRGaRfx1SHJQgq433KeXFYrLEqhQYel3a4uvy5DKBteJVMrbOpejml3ihyOO7dL4a+mcegRffqIA/Pmro8+3f+fnqg/3n0pppaofp3QA2SJblxlEvSRXk2cRc7XxPOMBa1WMCKJKnBugxMSdENT05pk1tbabhZGnUjHVU3ROaKNene9fgxROLjbpmGSEG5aOYCwGtDG2H+Gg/rOnlxBnBNVCDHXx+/777hMKvEBHmMXJ1ZF7akydoK+LHD3kk7Ku/mpTYX57p5HUyJv1U+78mYPHBqFNwGqpPj+j46AG2qVG2dzdi2tC1qV94QrkV+r7gOtMMAJKrtM=
